# docker-compose.yml

version: '3.8'
services:
  db:
    image: postgres:15 # PostgreSQL 15 버전의 이미지를 사용합니다.
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ai_dea_auction
    ports:
      # 컴퓨터에 이미 설치된 PostgreSQL과의 충돌을 피하기 위해
      # 외부 포트를 5433으로 설정합니다. (내부 포트는 5432 그대로 사용)
      - "5433:5432"
    volumes:
      # 데이터베이스 데이터를 컴퓨터에 저장하여 데이터 유실을 방지합니다.
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: