"use client"
import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ko"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.browse": "Browse Ideas",
    "nav.marketplace": "Marketplace",
    "nav.sell": "Sell Ideas",
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.welcome": "Welcome",
    "auth.welcomeBack": "Welcome back",
    "auth.createAccountDesc": "Please enter your details to create an account.",
    "auth.signInDesc": "Please enter your credentials to sign in.",
    "auth.continueWithGoogle": "Continue with Google",
    "auth.or": "or",
    "auth.name": "Name",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.signIn": "Sign in",
    "auth.createAccount": "Create account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.dontHaveAccount": "Don't have an account yet?",
    "footer.rights": "All rights reserved.",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.contact": "Contact",
    "footer.auctions": "Auctions",
    "footer.dispute": "Dispute Resolution",
    "footer.nda": "NDA Templates",
    "footer.help": "Help Center",
    "footer.faq": "FAQ",
    "footer.community": "Community",
    "language.select": "Select Language",
    "browse.title": "Browse AI Ideas",
    "browse.subtitle": "Explore innovative AI concepts from our creative community",
    "browse.totalIdeas": "Total Ideas",
    "browse.activeAuctions": "Active Auctions",
    "browse.contributors": "Contributors",
    "browse.avgRating": "Avg Rating",
    "browse.searchPlaceholder": "Search ideas, creators, or tags...",
    "browse.category": "Category",
    "browse.sortBy": "Sort By",
    "browse.allCategories": "All Categories",
    "browse.newest": "Newest First",
    "browse.popular": "Most Popular",
    "browse.trending": "Trending",
    "browse.highest-rated": "Highest Rated",
    "browse.inAuction": "In Auction",
    "browse.community": "Community",
    "browse.by": "by",
    "browse.viewDetails": "View Details",
    "browse.joinAuction": "Join Auction",
    "browse.startAuction": "Start Auction",
    "browse.loadMore": "Load More Ideas",
    "marketplace.title": "AI Idea Marketplace",
    "marketplace.subtitle": "Discover and acquire innovative AI concepts from creators worldwide",
    "marketplace.activeIdeas": "Active Ideas",
    "marketplace.totalVolume": "Total Volume",
    "marketplace.activeUsers": "Active Users",
    "marketplace.liveAuctions": "Live Auctions",
    "marketplace.avgRating": "Avg Rating",
    "marketplace.searchPlaceholder": "Search ideas, categories, or tags...",
    "marketplace.category": "Category",
    "marketplace.sortBy": "Sort By",
    "marketplace.filters": "Filters",
    "marketplace.advancedFilters": "Advanced Filters",
    "marketplace.priceRange": "Price Range",
    "marketplace.quickFilters": "Quick Filters",
    "marketplace.featuredIdeas": "Featured Ideas",
    "marketplace.highRevenue": "High Revenue Potential",
    "marketplace.lowCompetition": "Low Competition",
    "marketplace.status": "Status",
    "marketplace.hotIdeas": "Hot Ideas",
    "marketplace.endingSoon": "Ending Soon",
    "marketplace.newArrivals": "New Arrivals",
    "marketplace.showing": "Showing",
    "marketplace.of": "of",
    "marketplace.ideas": "ideas",
    "marketplace.view": "View:",
    "marketplace.grid": "Grid",
    "marketplace.list": "List",
    "marketplace.currentBid": "Current Bid",
    "marketplace.starting": "Starting",
    "marketplace.bids": "Bids",
    "marketplace.views": "Views",
    "marketplace.likes": "Likes",
    "marketplace.left": "left",
    "marketplace.by": "by",
    "marketplace.buyNow": "Buy Now",
    "marketplace.noIdeasFound": "No Ideas Found",
    "marketplace.noIdeasDesc": "Try adjusting your search criteria or browse different categories.",
    "marketplace.clearFilters": "Clear Filters",
    "marketplace.submitIdea": "Submit Your Idea",
    "marketplace.loadMore": "Load More Ideas",
    "purchase.title": "Purchase Idea",
    "purchase.verifyPayment": "Verify Payment Information",
    "purchase.paymentRequired": "Valid payment method required for secure transactions",
    "purchase.noPaymentInfo": "No Payment Method Found",
    "purchase.addPaymentInfo": "Please add a payment method to continue",
    "purchase.addPayment": "Add Payment Method",
    "purchase.paymentVerified": "Payment Method Verified",
    "purchase.proceedPayment": "Proceed to Payment",
    "purchase.securePayment": "Secure Payment",
    "purchase.timeRemaining": "Time Remaining",
    "purchase.cancel": "Cancel",
    "purchase.payNow": "Pay Now",
    "purchase.processing": "Processing Payment...",
    "purchase.doNotClose": "Please do not close this window",
    "purchase.success": "Payment Successful!",
    "purchase.successDesc": "You now own this AI idea. Check your dashboard for details.",
    "purchase.close": "Close",
    "purchase.viewIdea": "View Idea",
    "nda.title": "NDA Templates & Idea Protection Guide",
    "nda.subtitle": "Understanding the legal framework that protects your valuable ideas on our platform.",
    "nda.why_crucial": "Why is an NDA crucial on our platform?",
    "nda.description": "An NDA (Non-Disclosure Agreement) is the legal cornerstone of our marketplace. It's a binding contract that ensures your concepts are treated with the confidentiality they deserve. Every potential buyer must electronically sign this agreement before viewing the detailed specifics of an idea. This process transforms your concept into a legally protected asset.",
    "nda.standard_nda": "Our Standard NDA",
    "nda.clause1_title": "1. Definition of Confidential Information",
    "nda.clause1_legal": `"Confidential Information" shall include all information disclosed by the Idea Creator, including but not limited to the idea's description, attached documentation, technical specifications, business models, and any related notes or discussions conducted via the platform.`,
    "nda.clause1_plain": `Every piece of information you see related to the idea after agreeing to this NDA is considered a legally protected secret. This includes the description, any uploaded files, and even messages exchanged about the idea on our platform.`,
    "nda.clause2_title": "2. Obligation of Confidentiality",
    "nda.clause2_legal": `The Receiving Party shall hold and maintain the Confidential Information in strict confidence and shall not, without prior written consent, disclose any Confidential Information to any third party.`,
    "nda.clause2_plain": `If you view an idea, you cannot share its details with anyone else—not your colleagues, friends, or other companies—without the creator's explicit permission. The secret stops with you.`,
    "nda.clause3_title": "3. Non-Use Obligation",
    "nda.clause3_legal": `The Receiving Party agrees not to use the Confidential Information for any purpose other than to evaluate the potential for a transaction through the marketplace. The Receiving Party shall not use the Confidential Information for its own or any third party's commercial benefit.`,
    "nda.clause3_plain": `This is the most important rule. You cannot take the concept you've seen and start building it yourself or give it to your team to work on without officially acquiring the rights through an auction on our platform.`,
    "nda.what_this_means": "What this means:",
    "nda.download_button": "Download Standard NDA Template (PDF)",
    "nda.faq_title": "Frequently Asked Questions (FAQ)",
    "nda.faq1_q": "Is this electronic NDA legally binding?",
    "nda.faq1_a": "Yes. Modern electronic signature laws confirm that electronic agreements are legally valid. When a user agrees to an NDA, our platform securely logs the user's identity, the specific version of the agreement, a precise timestamp, and the associated IP address, creating a robust and verifiable audit trail.",
    "nda.faq2_q": "What happens if someone violates the NDA?",
    "nda.faq2_a": "If a creator believes their confidential information has been misused, the signed NDA and our audit trail provide the legal basis to take action against the violating party. Our platform will provide the necessary transaction and agreement logs to support a creator's claim in a formal dispute resolution process.",
    "nda.disclaimer_title": "Legal Disclaimer",
    "nda.disclaimer_text": "The information and templates provided on this page are for informational purposes only and do not constitute legal advice. Our platform is not a law firm. While our Standard NDA is a robust document designed to protect ideas within our marketplace, we strongly recommend consulting with a qualified legal professional for personalized advice regarding your specific intellectual property needs.",
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated",
    "terms.mainTitle": "AI-dea Auction Platform Terms of Service",
    "terms.mainDescription": "Please read these terms carefully before using our platform. By accessing or using AI-dea Auction, you agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    "terms.acceptance_title": "1. Acceptance of Terms",
    "terms.acceptance_p1": "By accessing and using the AI-dea Auction platform (“Service”), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    "terms.platformDesc_title": "2. Platform Description",
    "terms.platformDesc_p1": "AI-dea Auction is a marketplace platform that facilitates the buying and selling of innovative AI concepts and ideas. The platform provides tools for idea submission, auction management, legal protection, and secure transactions.",
    "terms.userResp_title": "3. User Responsibilities",
    "terms.userResp_p1": "Users are responsible for the accuracy and originality of the ideas they submit. Buyers are responsible for conducting their own due diligence before acquiring an idea. All users must adhere to our community guidelines and act in good faith.",
    "terms.ipProtection_title": "4. Intellectual Property Protection",
    "terms.ipProtection_p1": "Idea Creators retain full ownership of their intellectual property until a transaction is successfully completed. All viewers must agree to a legally binding Non-Disclosure Agreement (NDA) before accessing detailed information. The platform provides a secure environment but is not responsible for IP disputes between users.",
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated",
    "privacy.mainTitle": "AI-dea Auction Privacy Policy",
    "privacy.mainDescription": "We are committed to protecting your privacy and ensuring the security of your personal information and intellectual property.",
    "privacy.infoWeCollect_title": "1. Information We Collect",
    "privacy.infoWeCollect_p1_title": "1.1 Personal Information",
    "privacy.infoWeCollect_p1_l1": "Name, email address, and contact information",
    "privacy.infoWeCollect_p1_l2": "Payment and billing information",
    "privacy.infoWeCollect_p1_l3": "Professional background and company details",
    "privacy.infoWeCollect_p1_l4": "Identity verification documents",
    "privacy.infoWeCollect_p2_title": "1.2 Platform Activity",
    "privacy.infoWeCollect_p2_l1": "Ideas submitted and viewed",
    "privacy.infoWeCollect_p2_l2": "Bidding history and transaction records",
    "privacy.infoWeCollect_p2_l3": "Communication logs and messages",
    "privacy.infoWeCollect_p2_l4": "Login times and IP addresses",
    "privacy.infoWeCollect_p3_title": "1.3 Technical Information",
    "privacy.infoWeCollect_p3_l1": "Device and browser type",
    "privacy.infoWeCollect_p3_l2": "Usage data and cookies",
    "dispute.title": "Report a Dispute",
    "dispute.subtitle": "Report intellectual property violations, NDA breaches, or other legal concerns",
    "dispute.form_title": "Dispute Information",
    "dispute.form_subtitle": "Please provide detailed information about your dispute. All submissions are reviewed by our legal team.",
    "dispute.type": "Type of Dispute",
    "dispute.urgency": "Urgency Level",
    "dispute.ideaId": "Related Idea ID (if applicable)",
    "dispute.ideaId_placeholder": "Enter the ID of the related idea",
    "dispute.contactEmail": "Contact Email",
    "dispute.contactEmail_placeholder": "Enter your email address",
    "dispute.description": "Detailed Description",
    "dispute.description_placeholder": "Provide a detailed description of the dispute, including dates, parties involved, and specific violations",
    "dispute.evidence": "Supporting Evidence",
    "dispute.evidence_placeholder": "List any supporting evidence, documents, screenshots, or other materials that support your dispute",
    "dispute.agreement": "I agree to the dispute resolution process",
    "dispute.agreement_desc": "By submitting this dispute, you agree to participate in our resolution process and provide additional information as requested.",
    "dispute.submit": "Submit Dispute",
    "dispute.type_placeholder": "Select dispute type",
    "dispute.sidebar_legal_title": "Legal Protection",
    "dispute.sidebar_legal_p1": "Legal team response",
    "dispute.sidebar_legal_p2": "Activity logging",
    "dispute.sidebar_legal_p3": "Evidence retention",
    "dispute.sidebar_process_title": "Resolution Process",
    "dispute.sidebar_process_s1": "Initial Review",
    "dispute.sidebar_process_s2": "Investigation",
    "dispute.sidebar_process_s3": "Resolution",
    "dispute.sidebar_contact_title": "Emergency Contact",
    "dispute.sidebar_contact_desc": "For urgent legal matters requiring immediate attention:",
    "dispute.types.ip_violation": "Intellectual Property Violation",
    "dispute.types.nda_breach": "NDA Breach",
    "dispute.types.payment": "Payment Dispute",
    "dispute.types.manipulation": "Auction Manipulation",
    "dispute.types.fraud": "Fraudulent Activity",
    "dispute.types.policy_violation": "Platform Policy Violation",
    "dispute.types.other": "Other",
    "dispute.urgency_levels.low": "Low - Standard review",
    "dispute.urgency_levels.medium": "Medium - Standard dispute",
    "dispute.urgency_levels.high": "High - Urgent attention",
    "idea.overview": "Overview",
    "idea.tags": "Tags",
    "idea.technicalDetails": "Technical Details",
    "idea.marketPotential": "Market Potential",
    "idea.competitiveAdvantage": "Competitive Advantage",
    "idea.implementationPlan": "Implementation Plan",
    "idea.meta": "Meta",
    "idea.auction": "Auction",
    "idea.fields.owner": "Owner",
    "idea.fields.views": "Views",
    "idea.fields.likes": "Likes",
    "idea.fields.createdAt": "Created At",
    "idea.fields.updatedAt": "Updated At",
    "idea.fields.startingPrice": "Starting Price",
    "idea.fields.currentBid": "Current Bid",
    "idea.fields.startTime": "Start Time",
    "idea.fields.endTime": "End Time",
    "help.title": "Help Center",
    "help.subtitle": "Find answers to your questions and get the support you need.",
    "help.searchPlaceholder": "Search for topics...",
    "help.gettingStarted": "Getting Started",
    "help.forSellers": "For Idea Sellers",
    "help.forBidders": "For Bidders",
    "help.accountSecurity": "Account & Security",

    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Quick answers to common questions about our platform.",
    "faq.q1": "What is AI-dea Auction?",
    "faq.a1": "AI-dea Auction is a marketplace connecting innovators who have AI ideas with developers and entrepreneurs who can turn those ideas into reality. We provide a secure platform for buying and selling vetted AI concepts through auctions.",
    "faq.q2": "How is my Intellectual Property (IP) protected?",
    "faq.a2": "Every idea is protected by a mandatory Non-Disclosure Agreement (NDA) that all potential bidders must sign before viewing detailed information. We also log all access for a clear audit trail.",
    "faq.q3": "What are the fees for selling an idea?",
    "faq.a3": "We charge a commission fee only upon the successful sale of an idea. There are no upfront costs to list an idea. The commission structure is detailed in our Terms of Service.",
    "faq.q4": "How do auctions work?",
    "faq.a4": "Each idea is listed for a set duration (e.g., 7 days). Bidders place bids, and the highest bidder at the end of the auction wins the rights to the idea. All bids are binding.",

    "contact.title": "Contact Us",
    "contact.subtitle": "Have a question or need to get in touch? Fill out the form below.",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Your Message",
    "contact.form.submit": "Send Message",
    "contact.info.title": "Our Information",
    "contact.info.email": "support@ai-dea-auction.com",
    "contact.info.response": "We typically respond within 24 business hours."
    },
  ko: {
    "nav.home": "홈",
    "nav.browse": "아이디어 탐색",
    "nav.marketplace": "마켓플레이스",
    "nav.sell": "아이디어 판매",
    "auth.login": "로그인",
    "auth.signup": "회원가입",
    "auth.welcome": "환영합니다",
    "auth.welcomeBack": "다시 오신 것을 환영합니다",
    "auth.createAccountDesc": "계정을 생성하려면 정보를 입력해주세요.",
    "auth.signInDesc": "로그인하려면 인증 정보를 입력해주세요.",
    "auth.continueWithGoogle": "Google로 계속하기",
    "auth.or": "또는",
    "auth.name": "이름",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.confirmPassword": "비밀번호 확인",
    "auth.forgotPassword": "비밀번호를 잊으셨나요?",
    "auth.signIn": "로그인",
    "auth.createAccount": "계정 만들기",
    "auth.alreadyHaveAccount": "이미 계정이 있으신가요?",
    "auth.dontHaveAccount": "아직 계정이 없으신가요?",
    "footer.rights": "모든 권리 보유.",
    "footer.terms": "이용약관",
    "footer.privacy": "개인정보보호정책",
    "footer.contact": "연락처",
    "footer.auctions": "경매",
    "footer.dispute": "분쟁 해결",
    "footer.nda": "NDA 템플릿",
    "footer.help": "도움말 센터",
    "footer.faq": "자주 묻는 질문",
    "footer.community": "커뮤니티",
    "language.select": "언어 선택",
    "browse.title": "AI 아이디어 탐색",
    "browse.subtitle": "창의적인 커뮤니티의 혁신적인 AI 컨셉을 탐색해보세요",
    "browse.totalIdeas": "총 아이디어",
    "browse.activeAuctions": "활성 경매",
    "browse.contributors": "기여자",
    "browse.avgRating": "평균 평점",
    "browse.searchPlaceholder": "아이디어, 창작자, 태그 검색...",
    "browse.category": "카테고리",
    "browse.sortBy": "정렬 기준",
    "browse.allCategories": "모든 카테고리",
    "browse.newest": "최신순",
    "browse.popular": "인기순",
    "browse.trending": "트렌딩",
    "browse.highest-rated": "평점순",
    "browse.inAuction": "경매 중",
    "browse.community": "커뮤니티",
    "browse.by": "작성자",
    "browse.viewDetails": "상세보기",
    "browse.joinAuction": "경매 참여",
    "browse.startAuction": "경매 시작",
    "browse.loadMore": "더 많은 아이디어 로드",
    "marketplace.title": "AI 아이디어 마켓플레이스",
    "marketplace.subtitle": "전 세계 창작자들의 혁신적인 AI 컨셉을 발견하고 획득하세요",
    "marketplace.activeIdeas": "활성 아이디어",
    "marketplace.totalVolume": "총 거래량",
    "marketplace.activeUsers": "활성 사용자",
    "marketplace.liveAuctions": "실시간 경매",
    "marketplace.avgRating": "평균 평점",
    "marketplace.searchPlaceholder": "아이디어, 카테고리, 태그 검색...",
    "marketplace.category": "카테고리",
    "marketplace.sortBy": "정렬 기준",
    "marketplace.filters": "필터",
    "marketplace.advancedFilters": "고급 필터",
    "marketplace.priceRange": "가격 범위",
    "marketplace.quickFilters": "빠른 필터",
    "marketplace.featuredIdeas": "추천 아이디어",
    "marketplace.highRevenue": "높은 수익 잠재력",
    "marketplace.lowCompetition": "낮은 경쟁",
    "marketplace.status": "상태",
    "marketplace.hotIdeas": "인기 아이디어",
    "marketplace.endingSoon": "곧 종료",
    "marketplace.newArrivals": "신규 등록",
    "marketplace.showing": "표시 중",
    "marketplace.of": "총",
    "marketplace.ideas": "개 아이디어",
    "marketplace.view": "보기:",
    "marketplace.grid": "격자",
    "marketplace.list": "목록",
    "marketplace.currentBid": "현재 입찰가",
    "marketplace.starting": "시작가",
    "marketplace.bids": "입찰",
    "marketplace.views": "조회수",
    "marketplace.likes": "좋아요",
    "marketplace.left": "남음",
    "marketplace.by": "작성자",
    "marketplace.buyNow": "지금 구매",
    "marketplace.noIdeasFound": "아이디어를 찾을 수 없습니다",
    "marketplace.noIdeasDesc": "검색 조건을 조정하거나 다른 카테고리를 둘러보세요.",
    "marketplace.clearFilters": "필터 지우기",
    "marketplace.submitIdea": "아이디어 제출",
    "marketplace.loadMore": "더 많은 아이디어 로드",
    "purchase.title": "아이디어 구매",
    "purchase.verifyPayment": "결제 정보 확인",
    "purchase.paymentRequired": "안전한 거래를 위해 유효한 결제 수단이 필요합니다",
    "purchase.noPaymentInfo": "결제 수단을 찾을 수 없습니다",
    "purchase.addPaymentInfo": "계속하려면 결제 수단을 추가해주세요",
    "purchase.addPayment": "결제 수단 추가",
    "purchase.paymentVerified": "결제 수단이 확인되었습니다",
    "purchase.proceedPayment": "결제 진행",
    "purchase.securePayment": "안전한 결제",
    "purchase.timeRemaining": "남은 시간",
    "purchase.cancel": "취소",
    "purchase.payNow": "지금 결제",
    "purchase.processing": "결제 처리 중...",
    "purchase.doNotClose": "이 창을 닫지 마세요",
    "purchase.success": "결제 완료!",
    "purchase.successDesc": "이제 이 AI 아이디어를 소유하게 되었습니다. 자세한 내용은 대시보드를 확인하세요.",
    "purchase.close": "닫기",
    "purchase.viewIdea": "아이디어 보기",
    "nda.title": "NDA 템플릿 및 아이디어 보호 가이드",
    "nda.subtitle": "저희 플랫폼에서 당신의 소중한 아이디어를 보호하는 법적 체계를 이해하세요.",
    "nda.why_crucial": "왜 NDA가 저희 플랫폼에서 중요한가요?",
    "nda.description": "NDA(비밀유지계약)는 저희 마켓플레이스의 법적 초석입니다. 이는 거래가 이루어지기 전, 당신의 컨셉이 마땅히 받아야 할 기밀성과 존중을 보장하는 법적 구속력이 있는 계약입니다. 모든 잠재적 구매자는 아이디어의 상세 내용을 보기 전에 이 계약을 검토하고 전자 서명해야 합니다. 이 과정은 당신의 컨셉을 단순한 아이디어에서 법적으로 보호받는 자산으로 전환시킵니다.",
    "nda.standard_nda": "저희의 표준 NDA",
    "nda.clause1_title": "1. 비밀정보의 정의",
    "nda.clause1_legal": `"비밀정보"는 아이디어 제안자가 열람자에게 공개하는 모든 정보를 포함하며, 아이디어 설명, 첨부 문서, 기술 사양, 비즈니스 모델 및 플랫폼을 통해 이루어진 모든 관련 메모나 토론을 포함하되 이에 국한되지 않습니다.`,
    "nda.clause1_plain": `이 NDA에 동의한 후 보게 되는 아이디어와 관련된 모든 정보는 법적으로 보호받는 비밀로 간주됩니다. 여기에는 설명, 업로드된 파일, 플랫폼에서 아이디어에 관해 주고받은 메시지까지 포함됩니다.`,
    "nda.clause2_title": "2. 비밀유지 의무",
    "nda.clause2_legal": `정보 수신자는 비밀정보를 엄격하게 기밀로 유지해야 하며, 사전 서면 동의 없이는 어떠한 비밀정보도 제3자에게 공개할 수 없습니다.`,
    "nda.clause2_plain": `아이디어를 열람한 경우, 창작자의 명시적인 허가 없이는 동료, 친구 또는 다른 회사 등 다른 사람에게 그 내용을 공유할 수 없습니다. 비밀은 당신에게서 멈춥니다.`,
    "nda.clause3_title": "3. 사용금지 의무",
    "nda.clause3_legal": `정보 수신자는 마켓플레이스를 통한 거래 가능성을 평가하는 목적 외에 다른 목적으로 비밀정보를 사용하지 않을 것에 동의합니다. 정보 수신자는 자신이나 제3자의 상업적 이익을 위해 비밀정보를 사용할 수 없습니다.`,
    "nda.clause3_plain": `이것이 가장 중요한 규칙입니다. 저희 플랫폼에서 경매를 통해 공식적으로 권리를 획득하지 않고는, 당신이 본 컨셉을 가지고 직접 개발을 시작하거나 당신의 팀에게 작업을 지시할 수 없습니다.`,
    "nda.what_this_means": "이것이 의미하는 바는:",
    "nda.download_button": "표준 NDA 템플릿 다운로드 (PDF)",
    "nda.faq_title": "자주 묻는 질문 (FAQ)",
    "nda.faq1_q": "이 전자 NDA는 법적 구속력이 있나요?",
    "nda.faq1_a": "네. 현대의 전자서명법은 전자 계약 및 서명이 법적으로 유효함을 확인합니다. 사용자가 NDA에 동의하면, 저희 플랫폼은 사용자의 신원, 동의한 계약의 특정 버전, 정확한 타임스탬프 및 관련 IP 주소를 안전하게 기록하여 강력하고 검증 가능한 감사 추적을 생성합니다.",
    "nda.faq2_q": "누군가 NDA를 위반하면 어떻게 되나요?",
    "nda.faq2_a": "창작자가 자신의 비밀정보가 오용되었다고 생각하는 경우, 서명된 NDA와 저희의 감사 추적은 위반 당사자에 대해 법적 조치를 취할 수 있는 법적 근거를 제공합니다. 저희 플랫폼은 분쟁 해결 과정에서 창작자의 주장을 뒷받침하는 데 필요한 거래 및 동의 기록을 제공할 것입니다.",
    "nda.disclaimer_title": "법적 고지",
    "nda.disclaimer_text": "이 페이지에서 제공되는 정보와 템플릿은 정보 제공 목적으로만 사용되며, 법률 자문을 구성하지 않습니다. 저희 플랫폼은 법무법인이 아닙니다. 저희의 표준 NDA는 마켓플레이스 내에서 아이디어를 보호하기 위해 설계된 강력한 문서이지만, 특정 지적 재산권 요구에 대한 개인화된 조언을 위해서는 자격을 갖춘 법률 전문가와 상담할 것을 강력히 권장합니다.",
    "terms.title": "이용약관",
    "terms.lastUpdated": "최종 업데이트",
    "terms.mainTitle": "AI-dea Auction 플랫폼 서비스 이용약관",
    "terms.mainDescription": "저희 플랫폼을 사용하시기 전에 본 약관을 주의 깊게 읽어주십시오. AI-dea Auction에 접속하거나 사용함으로써, 귀하는 본 계약의 조건에 구속되는 데 동의하는 것으로 간주됩니다. 위 내용에 동의하지 않으시면, 본 서비스를 이용하지 마십시오.",
    "terms.acceptance_title": "1. 약관 동의",
    "terms.acceptance_p1": "AI-dea Auction 플랫폼('서비스')에 접속하고 사용함으로써, 귀하는 본 계약의 조건에 구속되는 데 동의합니다. 위 내용에 동의하지 않으시면, 본 서비스를 이용하지 마십시오.",
    "terms.platformDesc_title": "2. 플랫폼 설명",
    "terms.platformDesc_p1": "AI-dea Auction은 혁신적인 AI 컨셉과 아이디어의 구매 및 판매를 촉진하는 마켓플레이스 플랫폼입니다. 본 플랫폼은 아이디어 제출, 경매 관리, 법적 보호 및 안전한 거래를 위한 도구를 제공합니다.",
    "terms.userResp_title": "3. 사용자 책임",
    "terms.userResp_p1": "사용자는 자신이 제출하는 아이디어의 정확성과 독창성에 대한 책임이 있습니다. 구매자는 아이디어를 인수하기 전에 스스로 실사를 수행할 책임이 있습니다. 모든 사용자는 커뮤니티 가이드라인을 준수하고 신의성실의 원칙에 따라 행동해야 합니다.",
    "terms.ipProtection_title": "4. 지적 재산권 보호",
    "terms.ipProtection_p1": "아이디어 창작자는 거래가 성공적으로 완료될 때까지 자신의 지적 재산에 대한 완전한 소유권을 보유합니다. 모든 열람자는 상세 정보에 접근하기 전에 법적 구속력이 있는 비밀유지계약(NDA)에 동의해야 합니다. 플랫폼은 안전한 환경을 제공하지만, 사용자 간의 IP 분쟁에 대해서는 책임지지 않습니다.",
    "privacy.title": "개인정보처리방침",
    "privacy.lastUpdated": "최종 업데이트",
    "privacy.mainTitle": "AI-dea Auction 개인정보처리방침",
    "privacy.mainDescription": "저희는 귀하의 개인정보를 보호하고, 개인 정보 및 지적 재산의 보안을 보장하기 위해 최선을 다하고 있습니다.",
    "privacy.infoWeCollect_title": "1. 수집하는 정보",
    "privacy.infoWeCollect_p1_title": "1.1 개인 정보",
    "privacy.infoWeCollect_p1_l1": "이름, 이메일 주소 및 연락처 정보",
    "privacy.infoWeCollect_p1_l2": "결제 및 청구 정보",
    "privacy.infoWeCollect_p1_l3": "전문적인 배경 및 회사 세부 정보",
    "privacy.infoWeCollect_p1_l4": "신원 확인 서류",
    "privacy.infoWeCollect_p2_title": "1.2 플랫폼 활동",
    "privacy.infoWeCollect_p2_l1": "제출 및 조회한 아이디어",
    "privacy.infoWeCollect_p2_l2": "입찰 내역 및 거래 기록",
    "privacy.infoWeCollect_p2_l3": "커뮤니케이션 로그 및 메시지",
    "privacy.infoWeCollect_p2_l4": "로그인 시간 및 IP 주소",
    "privacy.infoWeCollect_p3_title": "1.3 기술 정보",
    "privacy.infoWeCollect_p3_l1": "기기 및 브라우저 유형",
    "privacy.infoWeCollect_p3_l2": "사용 데이터 및 쿠키",
    "dispute.title": "분쟁 신고하기",
    "dispute.subtitle": "지적 재산권 침해, NDA 위반 또는 기타 법적 문제를 신고해주세요",
    "dispute.form_title": "분쟁 정보",
    "dispute.form_subtitle": "분쟁에 대한 자세한 정보를 제공해주세요. 모든 제출물은 저희 법무팀이 검토합니다.",
    "dispute.type": "분쟁 유형",
    "dispute.urgency": "긴급도",
    "dispute.ideaId": "관련 아이디어 ID (해당하는 경우)",
    "dispute.ideaId_placeholder": "관련 아이디어의 ID를 입력하세요",
    "dispute.contactEmail": "연락용 이메일",
    "dispute.contactEmail_placeholder": "이메일 주소를 입력하세요",
    "dispute.description": "상세 설명",
    "dispute.description_placeholder": "날짜, 관련 당사자, 특정 위반 사항을 포함하여 분쟁에 대해 자세히 설명해주세요",
    "dispute.evidence": "증거 자료",
    "dispute.evidence_placeholder": "귀하의 주장을 뒷받침하는 증거, 문서, 스크린샷 또는 기타 자료를 나열해주세요",
    "dispute.agreement": "분쟁 해결 절차에 동의합니다",
    "dispute.agreement_desc": "이 분쟁을 제출함으로써 귀하는 당사의 해결 절차에 참여하고 요청 시 추가 정보를 제공하는 데 동의하게 됩니다.",
    "dispute.submit": "분쟁 제출하기",
    "dispute.type_placeholder": "분쟁 유형을 선택하세요",
    "dispute.sidebar_legal_title": "법적 보호",
    "dispute.sidebar_legal_p1": "법무팀 응답",
    "dispute.sidebar_legal_p2": "활동 기록",
    "dispute.sidebar_legal_p3": "증거 보존",
    "dispute.sidebar_process_title": "해결 절차",
    "dispute.sidebar_process_s1": "초기 검토",
    "dispute.sidebar_process_s2": "조사",
    "dispute.sidebar_process_s3": "해결",
    "dispute.sidebar_contact_title": "긴급 연락처",
    "dispute.sidebar_contact_desc": "즉각적인 조치가 필요한 긴급한 법적 문제의 경우:",
    "dispute.types.ip_violation": "지적 재산권 침해",
    "dispute.types.nda_breach": "NDA 위반",
    "dispute.types.payment": "결제 분쟁",
    "dispute.types.manipulation": "경매 조작",
    "dispute.types.fraud": "사기 행위",
    "dispute.types.policy_violation": "플랫폼 정책 위반",
    "dispute.types.other": "기타",
    "dispute.urgency_levels.low": "낮음 - 일반 검토",
    "dispute.urgency_levels.medium": "중간 - 표준 분쟁",
    "dispute.urgency_levels.high": "높음 - 긴급",
    "idea.overview": "개요",
    "idea.tags": "태그",
    "idea.technicalDetails": "기술 상세",
    "idea.marketPotential": "시장성",
    "idea.competitiveAdvantage": "경쟁 우위",
    "idea.implementationPlan": "구현 계획",
    "idea.meta": "메타",
    "idea.auction": "경매",
    "idea.fields.owner": "작성자",
    "idea.fields.views": "조회수",
    "idea.fields.likes": "좋아요",
    "idea.fields.createdAt": "생성일",
    "idea.fields.updatedAt": "수정일",
    "idea.fields.startingPrice": "시작가",
    "idea.fields.currentBid": "현재가",
    "idea.fields.startTime": "시작 시간",
    "idea.fields.endTime": "종료 시간",
    "help.title": "도움말 센터",
    "help.subtitle": "궁금한 점에 대한 답변을 찾고 필요한 지원을 받으세요.",
    "help.searchPlaceholder": "주제 검색...",
    "help.gettingStarted": "시작하기",
    "help.forSellers": "아이디어 판매자 가이드",
    "help.forBidders": "입찰자 가이드",
    "help.accountSecurity": "계정 및 보안",

    "faq.title": "자주 묻는 질문",
    "faq.subtitle": "플랫폼에 대한 일반적인 질문에 대한 빠른 답변입니다.",
    "faq.q1": "AI-dea Auction은 어떤 서비스인가요?",
    "faq.a1": "AI-dea Auction은 AI 아이디어를 가진 혁신가와 그 아이디어를 현실로 만들 수 있는 개발자 및 사업가를 연결하는 마켓플레이스입니다. 저희는 검증된 AI 컨셉을 경매를 통해 안전하게 거래할 수 있는 플랫폼을 제공합니다.",
    "faq.q2": "제 지적 재산권(IP)은 어떻게 보호되나요?",
    "faq.a2": "모든 아이디어는 잠재적 입찰자가 상세 정보를 보기 전에 반드시 서명해야 하는 비밀유지계약(NDA)에 의해 보호됩니다. 또한 모든 접근 기록을 로그로 남겨 명확한 감사 추적을 제공합니다.",
    "faq.q3": "아이디어 판매 수수료는 어떻게 되나요?",
    "faq.a3": "아이디어 등록 비용은 없으며, 아이디어가 성공적으로 판매되었을 때만 수수료가 부과됩니다. 자세한 수수료 정책은 이용약관에 명시되어 있습니다.",
    "faq.q4": "경매는 어떻게 진행되나요?",
    "faq.a4": "각 아이디어는 정해진 기간(예: 7일) 동안 경매에 부쳐집니다. 입찰자들은 입찰가를 제시하며, 경매 종료 시 가장 높은 가격을 제시한 입찰자가 아이디어에 대한 권리를 획득합니다. 모든 입찰은 법적 구속력을 가집니다.",

    "contact.title": "문의하기",
    "contact.subtitle": "질문이 있거나 문의가 필요한 경우 아래 양식을 작성해주세요.",
    "contact.form.name": "이름",
    "contact.form.email": "이메일",
    "contact.form.subject": "제목",
    "contact.form.message": "메시지",
    "contact.form.submit": "메시지 보내기",
    "contact.info.title": "연락처 정보",
    "contact.info.email": "support@ai-dea-auction.com",
    "contact.info.response": "보통 24시간(영업일 기준) 이내에 답변드립니다."
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem("ai-auction-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("ai-auction-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
